#!/bin/bash
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-2.0-or-later

set -euo pipefail

# Mixar Build Script
# Builds Blender (always Release) + Mixar (environment from settings.sh)

# Load all settings from settings.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/settings.sh"

# Use MIXAR_ENV directly from settings.sh (already exported there)
# Blender always builds in Release mode for optimal performance
BLENDER_BUILD_ENV="Release"

# Define build directory for this environment
BUILD_ENV_DIR="${BUILD_DIR}/${MIXAR_ENV}"

# Overlay Mixar sources onto source
echo "Overlaying Mixar sources onto source..."
"$SCRIPT_DIR/overlay.sh"

# Configure build directory
mkdir -p "${BUILD_ENV_DIR}"

# Generate environment configuration header
echo "Generating environment configuration for: $MIXAR_ENV"
mkdir -p "$SOURCE_DIR/source/creator"
cat > "$SOURCE_DIR/source/creator/mixar_env_config.h" << EOF
#pragma once
// Auto-generated file - DO NOT EDIT
// Generated for environment: $MIXAR_ENV

#define MIXAR_BASE_URL "$MIXAR_BACKEND_URL"
#define MIXAR_FRONTEND_BASE_URL "$MIXAR_FRONTEND_URL"
#define MIXAR_CURRENT_ENV "$MIXAR_ENV"

// Environment-specific macros for conditional compilation
EOF

# Generate environment-specific macro based on current MIXAR_ENV
case "$MIXAR_ENV" in
    "Prod")
        echo "#define MIXAR_ENV_PROD" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    "Dev")
        echo "#define MIXAR_ENV_DEV" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    "UAT"|"Uat")
        echo "#define MIXAR_ENV_UAT" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    *)
        echo "#define MIXAR_ENV_PROD  // Default to production for unknown environment" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
esac

# Emit the build-frozen Python env marker (mirrors mixar_env_config.h on the
# Python side). Used by mixar.config.config.get_dev_bypass_credentials() to
# gate the dev bypass behind a value that cannot be flipped by editing the
# bundled mixar.json. Only Dev builds get DEV_BYPASS_ALLOWED=True.
if [ "$MIXAR_ENV" = "Dev" ]; then
    BUILD_ENV_DEV_BYPASS="True"
else
    BUILD_ENV_DEV_BYPASS="False"
fi
mkdir -p "$SOURCE_DIR/scripts/mixar/config"
cat > "$SOURCE_DIR/scripts/mixar/config/_build_env.py" << EOF
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
# SPDX-License-Identifier: GPL-2.0-or-later
# Auto-generated by scripts/unix/build.sh - DO NOT EDIT
BUILD_ENVIRONMENT = "$MIXAR_ENV"
DEV_BYPASS_ALLOWED = $BUILD_ENV_DEV_BYPASS
EOF

# Drop cache entries that resolved into a different SDK than the one we build
# against. CMake never re-runs find_library() for an already-cached variable,
# so a cache configured without SDKROOT keeps its Command Line Tools framework
# paths forever. Those live outside -isysroot, so CMake passes them as explicit
# -F paths, which demotes their headers from system to user headers and lets
# -Werror=unguarded-availability-new fail the Cycles Metal build. Purging by
# value re-resolves them on this configure; the deployment-target gap that
# actually trips the warning is unchanged.
# Matches on whole SDK paths rather than a value prefix: entries such as
# *_LIB_DEPENDS legitimately list several correct SDK paths mid-value, and a
# prefix test flags every one of them on an already-healthy cache.
CMAKE_CACHE_FILE="$BUILD_ENV_DIR/CMakeCache.txt"

# Pin Blender's SDK lookup when settings.sh had to reject the default SDK.
# platform_apple_xcode.cmake honours a pre-defined OSX_SYSTEM and otherwise
# FORCE-sets CMAKE_OSX_SYSROOT from `xcrun --show-sdk-version`, which would
# drag the unusable SDK back in at compile/link time even though the SDKROOT
# we exported made CMake's own compiler checks pass. Empty on a healthy
# machine, so the configure lines are unchanged there. Passed on the
# cache-purge configures too: a cache left by a configure that died on the
# bad SDK has no OSX_SYSTEM yet, and a purge run without the pin re-detects
# that SDK and aborts the build before the real configure is reached.
SDK_PIN_ARGS=()
if [[ "$PLATFORM" == "macOS" && -n "${MIXAR_OSX_SDK_VERSION:-}" ]]; then
    SDK_PIN_ARGS+=("-DOSX_SYSTEM=$MIXAR_OSX_SDK_VERSION")
    echo "Pinning Blender's macOS SDK lookup to $MIXAR_OSX_SDK_VERSION"
fi
if [[ "$PLATFORM" == "macOS" && -n "${SDKROOT:-}" && -f "$CMAKE_CACHE_FILE" ]]; then
    STALE_SDK_VARS=()
    while read -r cache_var; do
        [[ -n "$cache_var" ]] && STALE_SDK_VARS+=("-U$cache_var")
    done < <(
        grep -E '^[A-Za-z_0-9]+:[A-Z]+=' "$CMAKE_CACHE_FILE" \
            | awk -v sdk="$SDKROOT" '
                {
                    var = $0; sub(/:.*/, "", var); rest = $0; stale = 0
                    while (match(rest, /\/[^ ";=[\]]*SDKs\/MacOSX[^ ";=[\]\/]*\.sdk/)) {
                        if (substr(rest, RSTART, RLENGTH) != sdk) stale = 1
                        rest = substr(rest, RSTART + RLENGTH)
                    }
                    if (stale) print var
                }' \
            | sort -u
    )
    if (( ${#STALE_SDK_VARS[@]} > 0 )); then
        echo "Purging ${#STALE_SDK_VARS[@]} CMake cache entries resolved outside $SDKROOT"
        cmake -S "$SOURCE_DIR" -B "$BUILD_ENV_DIR" "${SDK_PIN_ARGS[@]+"${SDK_PIN_ARGS[@]}"}" "${STALE_SDK_VARS[@]}" >/dev/null
    fi
fi

# Drop cached Python entries left behind by a different interpreter version.
# PYTHON_VERSION is a plain CACHE STRING that FindPythonLibsUnix only ever
# *defaults*, so a cache configured against a Blender release with an older
# Python (5.0 -> 3.11) keeps that value after the tree moves on (5.2 -> 3.13)
# and configure hard-fails with "At least Python 3.13 is required to build, but
# found Python 3.11". build/ and source/ are shared across branches, so a
# `git pull` that moves the upstream pin is enough to land in that state.
# Matching by value rather than by a hand-written variable list: the version is
# baked into every derived path (interpreter, headers, libpython, and the numpy
# include dir that audaspace compiles against), and purging only the obvious
# PYTHON_* names leaves the rest stale for the next compile to trip over.
if [[ -f "$CMAKE_CACHE_FILE" ]]; then
    CACHED_PYTHON_VERSION="$(
        sed -n 's/^PYTHON_VERSION:STRING=//p' "$CMAKE_CACHE_FILE" | head -n1
    )"
    if [[ -n "$CACHED_PYTHON_VERSION" && "$CACHED_PYTHON_VERSION" != "$PYTHON_VERSION" ]]; then
        STALE_PYTHON_VARS=("-UPYTHON_VERSION")
        while read -r cache_var; do
            [[ -n "$cache_var" ]] && STALE_PYTHON_VARS+=("-U$cache_var")
        done < <(
            grep -E '^[A-Za-z_0-9]+:[A-Z]+=' "$CMAKE_CACHE_FILE" \
                | awk -v want="$PYTHON_VERSION" '
                    {
                        var = $0; sub(/:.*/, "", var); rest = $0; stale = 0
                        while (match(rest, /python-?3\.[0-9]+/)) {
                            found = substr(rest, RSTART, RLENGTH)
                            sub(/^python-?/, "", found)
                            if (found != want) stale = 1
                            rest = substr(rest, RSTART + RLENGTH)
                        }
                        if (stale) print var
                    }' \
                | sort -u
        )
        echo "Purging ${#STALE_PYTHON_VARS[@]} CMake cache entries left on Python $CACHED_PYTHON_VERSION (this tree builds against Python $PYTHON_VERSION)"
        cmake -S "$SOURCE_DIR" -B "$BUILD_ENV_DIR" "${SDK_PIN_ARGS[@]+"${SDK_PIN_ARGS[@]}"}" "${STALE_PYTHON_VARS[@]}" >/dev/null
    fi
fi

# A configure that dies before Blender's CMakeLists.txt reaches its install
# prefix logic (e.g. on the SDK failure above) still caches CMake's bare
# default, CMAKE_INSTALL_PREFIX=/usr/local. Blender only replaces that when
# CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT is set, which CMake does on the
# FIRST configure only, so every later `make build` compiles fine and then
# fails installing into /usr/local. Dropping the entry makes the next
# configure initialize it again and hand it back to Blender's default.
if [[ -f "$CMAKE_CACHE_FILE" ]] \
    && grep -q -E '^CMAKE_INSTALL_PREFIX:PATH=(/usr/local|C:/Program Files[^=]*)$' "$CMAKE_CACHE_FILE"; then
    echo "Dropping CMake's default install prefix left by an aborted configure"
    cmake -S "$SOURCE_DIR" -B "$BUILD_ENV_DIR" "${SDK_PIN_ARGS[@]+"${SDK_PIN_ARGS[@]}"}" -UCMAKE_INSTALL_PREFIX >/dev/null
fi

# Configure with CMake (all platform logic handled in settings.sh)
echo "Configuring Mixar build - Blender: $BLENDER_BUILD_ENV, Mixar Environment: $MIXAR_ENV for $PLATFORM..."
cmake -C "$CMAKE_DIR/mixar_overrides.cmake" \
    $CMAKE_GENERATOR_ARGS \
    -S "$SOURCE_DIR" \
    -B "$BUILD_ENV_DIR" \
    "${SDK_PIN_ARGS[@]+"${SDK_PIN_ARGS[@]}"}" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# Build (all platform-specific args handled in settings.sh)
echo "Building Blender in $BLENDER_BUILD_ENV mode for Mixar environment: $MIXAR_ENV"
echo "Using $BUILD_CORES cores for parallel build"
cmake --build "$BUILD_ENV_DIR" $BUILD_ARGS
cmake --build "$BUILD_ENV_DIR" --target install --config "$BLENDER_BUILD_ENV"

# Resource root of the installed tree. macOS nests it inside the .app bundle;
# Linux installs flat under bin/. Both the runtime config and the embedded
# Python live under it, so resolve it once.
if [[ "$PLATFORM" == "macOS" ]]; then
    RESOURCE_BASE="$BUILD_ENV_DIR/bin/Mixar.app/Contents/Resources"
elif [[ "$PLATFORM" == "Linux" ]]; then
    RESOURCE_BASE="$BUILD_ENV_DIR/bin"
else
    echo "Error: Unsupported platform: $PLATFORM"
    exit 1
fi

# Generate runtime configuration for the bundle
echo "Generating runtime configuration for bundle..."
BUNDLE_CONFIG_DIR="$RESOURCE_BASE/$BLENDER_VERSION/config"
python3 "$ROOT_DIR/scripts/generate_config.py" --output "$BUNDLE_CONFIG_DIR/mixar.json"

# Install Python packages using the generated Python binary
echo "Installing Python packages for Mixar..."
PY_BASE="$RESOURCE_BASE"

# Try common python binary names inside Blender's embedded Python
PYTHON_BIN=""
for candidate in \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python${PYTHON_VERSION}" \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python3" \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python"; do
    if [[ -x "$candidate" ]]; then
        PYTHON_BIN="$candidate"
        break
    fi
done

SITE_PACKAGES="$PY_BASE/$BLENDER_VERSION/python/lib/python${PYTHON_VERSION}/site-packages"
REQUIREMENTS_FILE="$(dirname "$SCRIPT_DIR")/python_requirements.txt"

if [[ -n "$PYTHON_BIN" ]]; then
    echo "Found Python binary: $PYTHON_BIN"
    mkdir -p "$SITE_PACKAGES"
    
    # Check if requirements file exists
    if [[ -f "$REQUIREMENTS_FILE" ]]; then
        echo "Installing packages from: $REQUIREMENTS_FILE"
        
        # Force pip to install to the embedded Python's site-packages
        # Use --no-user to prevent installation to user site-packages
        # Use --target to specify the exact location
        if "$PYTHON_BIN" -m pip install --no-user --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
            echo "Successfully installed Python packages to embedded Python site-packages"
            # truststore is what lets the app trust corporate root CAs; a
            # silent fallback to certifi would only surface at a customer.
            if ! "$PYTHON_BIN" -c "import truststore" 2>/dev/null; then
                echo "Error: truststore installed but not importable from the embedded Python"
                exit 1
            fi
        elif command -v pip3 >/dev/null 2>&1; then
            echo "Embedded pip failed, trying system pip with --target..."
            if pip3 install --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
                echo "Successfully installed Python packages using system pip"
            else
                echo "Warning: Failed to install Python packages from requirements file"
            fi
        else
            echo "Warning: No pip available, skipping Python package installation"
        fi
    else
        echo "Warning: Requirements file not found at: $REQUIREMENTS_FILE"
        exit 1
    fi
else
    echo "Warning: Python binary not found under: $PY_BASE/$BLENDER_VERSION/python/bin"
fi

# Re-sign the dev build with a stable identity so macOS Keychain "Always
# Allow" persists across rebuilds (opt-in via MIXAR_DEV_SIGN_ID in .env; see
# scripts/unix/setup_dev_codesign.sh). Without this the linker's ad-hoc
# signature changes every build, and Keychain re-prompts for the
# MixarSafeStorage login tokens on each rebuild. Only the main executable is
# signed — the process's code identity is what Keychain ACLs match on.
# Release/notarization signing lives in package.sh and is unaffected.
if [[ "$PLATFORM" == "macOS" && -n "${MIXAR_DEV_SIGN_ID:-}" ]]; then
    MIXAR_APP_BINARY="$BUILD_ENV_DIR/bin/Mixar.app/Contents/MacOS/Mixar"
    # get-task-allow keeps the binary attachable by lldb, matching what an
    # ad-hoc dev signature allows.
    DEV_SIGN_ENTITLEMENTS="$BUILD_ENV_DIR/dev_codesign_entitlements.plist"
    cat > "$DEV_SIGN_ENTITLEMENTS" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.get-task-allow</key>
    <true/>
</dict>
</plist>
EOF
    echo "Signing dev build with identity: $MIXAR_DEV_SIGN_ID"
    if codesign --force --sign "$MIXAR_DEV_SIGN_ID" \
        --entitlements "$DEV_SIGN_ENTITLEMENTS" "$MIXAR_APP_BINARY"; then
        echo "Dev codesign OK — Keychain 'Always Allow' will persist across rebuilds."
    else
        echo "Warning: dev codesign failed. The build is still usable, but Keychain"
        echo "will re-prompt after every rebuild. Create the identity with:"
        echo "  ./scripts/unix/setup_dev_codesign.sh"
    fi
fi

# Done
echo "=== Build Complete ==="
echo "Python packages installed from: $REQUIREMENTS_FILE"
echo "Run Mixar using: $BUILD_ENV_DIR/bin/Mixar.app/Contents/MacOS/Mixar"